// apps/web-admin/src/views/admin/psychologist/ProfileAudit.vue
<template>
  <div class="profile-audit-page">
    <!-- 页面标题 -->
    <div class="page-header">
      <h2>资料审核管理</h2>
      <div class="audit-stats">
        <div class="stat-item pending">
          <span class="label">待审核</span>
          <span class="value">{{ statsData.pendingCount }}</span>
        </div>
        <div class="stat-item approved">
          <span class="label">已通过</span>
          <span class="value">{{ statsData.approvedCount }}</span>
        </div>
        <div class="stat-item rejected">
          <span class="label">已拒绝</span>
          <span class="value">{{ statsData.rejectedCount }}</span>
        </div>
      </div>
    </div>

    <!-- 筛选工具栏 -->
    <div class="filter-toolbar">
      <el-select v-model="statusFilter" placeholder="审核状态" clearable @change="handleSearch" style="width: 150px;">
        <el-option label="全部" :value="null"></el-option>
        <el-option label="待审核" :value="0"></el-option>
        <el-option label="已通过" :value="1"></el-option>
        <el-option label="已拒绝" :value="2"></el-option>
      </el-select>
      <el-button @click="handleReset">
        <el-icon><Refresh /></el-icon> 重置
      </el-button>
    </div>

    <!-- 数据表格 -->
    <el-table :data="auditList" v-loading="loading" stripe>
      <el-table-column prop="id" label="ID" width="80"></el-table-column>
      <el-table-column label="咨询师信息" min-width="180">
        <template #default="scope">
          <div class="psychologist-info">
            <el-avatar :size="36" :src="scope.row.userAvatar">
              <el-icon><User /></el-icon>
            </el-avatar>
            <div class="info-detail">
              <div class="name">{{ scope.row.psychologistName || '-' }}</div>
              <div class="username">{{ scope.row.userNickname || '-' }}</div>
            </div>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="变更字段" width="120">
        <template #default="scope">
          <el-tag type="info" size="small">{{ scope.row.fieldNameText || scope.row.fieldName }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="变更内容" min-width="160">
        <template #default="scope">
          <div class="change-content">
            <div class="change-item">
              <span class="label">原值：</span>
              <span class="value old">{{ scope.row.oldValue || '(空)' }}</span>
            </div>
            <div class="change-item">
              <span class="label">新值：</span>
              <span class="value new">{{ scope.row.newValue || '(空)' }}</span>
            </div>
            <div v-if="scope.row.reason" class="change-item">
              <span class="label">理由：</span>
              <span class="value reason">{{ scope.row.reason }}</span>
            </div>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="证明材料" width="80">
        <template #default="scope">
          <el-button
            v-if="scope.row.proofUrls"
            size="small"
            type="primary"
            link
            @click="handleViewProof(scope.row)"
          >
            查看
          </el-button>
          <span v-else class="no-proof">-</span>
        </template>
      </el-table-column>
      <el-table-column label="审核状态" width="90">
        <template #default="scope">
          <el-tag :type="getStatusType(scope.row.auditStatus)" size="small">
            {{ scope.row.auditStatusText || getStatusText(scope.row.auditStatus) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="申请时间" width="150">
        <template #default="scope">
          <span>{{ scope.row.createTime || '-' }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200" fixed="right">
        <template #default="scope">
          <template v-if="scope.row.auditStatus === 0">
            <el-button size="small" type="primary" @click="handleApprove(scope.row)">
              通过
            </el-button>
            <el-button size="small" type="danger" @click="handleReject(scope.row)">
              拒绝
            </el-button>
          </template>
          <el-button size="small" @click="handleViewDetail(scope.row)">
            详情
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <div class="pagination-wrapper">
      <el-pagination
        v-model:current-page="currentPage"
        v-model:page-size="pageSize"
        :total="total"
        :page-sizes="[10, 20, 50]"
        layout="total, sizes, prev, pager, next, jumper"
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
      />
    </div>

    <!-- 详情对话框 -->
    <el-dialog v-model="detailDialogVisible" title="审核详情" width="600px">
      <div v-if="currentAudit" class="detail-content">
        <el-descriptions :column="2" border>
          <el-descriptions-item label="咨询师">{{ currentAudit.psychologistName || '-' }}</el-descriptions-item>
          <el-descriptions-item label="变更字段">{{ currentAudit.fieldNameText || currentAudit.fieldName }}</el-descriptions-item>
          <el-descriptions-item label="原值" :span="2">
            <span class="value old">{{ currentAudit.oldValue || '(空)' }}</span>
          </el-descriptions-item>
          <el-descriptions-item label="新值" :span="2">
            <span class="value new">{{ currentAudit.newValue || '(空)' }}</span>
          </el-descriptions-item>
          <el-descriptions-item label="申请理由" :span="2">{{ currentAudit.reason || '-' }}</el-descriptions-item>
          <el-descriptions-item label="审核状态">
            <el-tag :type="getStatusType(currentAudit.auditStatus)" size="small">
              {{ currentAudit.auditStatusText || getStatusText(currentAudit.auditStatus) }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="申请时间">{{ currentAudit.createTime || '-' }}</el-descriptions-item>
          <el-descriptions-item label="审核时间" :span="2">{{ currentAudit.auditTime || '-' }}</el-descriptions-item>
          <el-descriptions-item label="审核备注" :span="2">{{ currentAudit.auditRemark || '-' }}</el-descriptions-item>
        </el-descriptions>

        <!-- 证明材料 -->
        <div v-if="currentAudit.proofUrls" class="proof-section">
          <h4>证明材料</h4>
          <div class="proof-images">
            <el-image
              v-for="(url, index) in parseProofUrls(currentAudit.proofUrls)"
              :key="index"
              :src="url"
              :preview-src-list="parseProofUrls(currentAudit.proofUrls)"
              fit="contain"
              style="width: 100px; height: 100px; margin-right: 10px; border-radius: 4px;"
            />
          </div>
        </div>
      </div>
    </el-dialog>

    <!-- 审核对话框 -->
    <el-dialog v-model="auditDialogVisible" :title="auditAction === 'approve' ? '通过审核' : '拒绝审核'" width="500px">
      <el-form :model="auditForm" label-width="100px">
        <el-form-item label="审核备注">
          <el-input
            v-model="auditForm.remark"
            type="textarea"
            :rows="3"
            :placeholder="auditAction === 'approve' ? '可选：添加通过备注' : '请输入拒绝原因'"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="auditDialogVisible = false">取消</el-button>
        <el-button :type="auditAction === 'approve' ? 'primary' : 'danger'" @click="confirmAudit" :loading="auditLoading">
          确认{{ auditAction === 'approve' ? '通过' : '拒绝' }}
        </el-button>
      </template>
    </el-dialog>

    <!-- 证明材料查看对话框 -->
    <el-dialog v-model="proofDialogVisible" title="证明材料" width="800px">
      <div class="proof-gallery">
        <el-image
          v-for="(url, index) in currentProofUrls"
          :key="index"
          :src="url"
          :preview-src-list="currentProofUrls"
          fit="contain"
          style="width: 100%; margin-bottom: 10px;"
        />
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  Refresh, User
} from '@element-plus/icons-vue'
import {
  getProfileAuditList,
  getProfileAuditDetail,
  approveProfileAudit,
  rejectProfileAudit
} from '@/api/psychologistAdmin'

const loading = ref(false)
const auditLoading = ref(false)
const statusFilter = ref<number | null>(null)
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)
const auditList = ref<any[]>([])

const statsData = reactive({
  pendingCount: 0,
  approvedCount: 0,
  rejectedCount: 0
})

const detailDialogVisible = ref(false)
const auditDialogVisible = ref(false)
const proofDialogVisible = ref(false)
const currentAudit = ref<any>(null)
const currentProofUrls = ref<string[]>([])
const auditAction = ref<'approve' | 'reject'>('approve')
const auditForm = reactive({
  remark: ''
})

// 获取列表数据
const fetchList = async () => {
  loading.value = true
  try {
    const params: any = {
      page: currentPage.value,
      size: pageSize.value
    }
    if (statusFilter.value !== null) {
      params.status = statusFilter.value
    }

    const res: any = await getProfileAuditList(params)
    if (res.code === 200) {
      auditList.value = res.data?.records || []
      total.value = res.data?.total || 0

      // 统计计算
      const list = res.data?.records || []
      statsData.pendingCount = list.filter((a: any) => a.auditStatus === 0).length
      statsData.approvedCount = list.filter((a: any) => a.auditStatus === 1).length
      statsData.rejectedCount = list.filter((a: any) => a.auditStatus === 2).length
    } else {
      ElMessage.error(res.message || '获取列表失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message || '获取列表失败')
  } finally {
    loading.value = false
  }
}

// 获取状态类型
const getStatusType = (status: number) => {
  switch (status) {
    case 0: return 'warning'
    case 1: return 'success'
    case 2: return 'danger'
    default: return 'info'
  }
}

// 获取状态文本
const getStatusText = (status: number) => {
  switch (status) {
    case 0: return '待审核'
    case 1: return '已通过'
    case 2: return '已拒绝'
    default: return '未知'
  }
}

// 搜索
const handleSearch = () => {
  currentPage.value = 1
  fetchList()
}

// 重置
const handleReset = () => {
  statusFilter.value = null
  currentPage.value = 1
  fetchList()
}

// 分页
const handleSizeChange = () => {
  currentPage.value = 1
  fetchList()
}

const handleCurrentChange = () => {
  fetchList()
}

// 查看详情
const handleViewDetail = async (row: any) => {
  try {
    const res: any = await getProfileAuditDetail(row.id)
    if (res.code === 200) {
      currentAudit.value = res.data
      detailDialogVisible.value = true
    } else {
      ElMessage.error(res.message || '获取详情失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message || '获取详情失败')
  }
}

// 查看证明材料
const handleViewProof = (row: any) => {
  currentProofUrls.value = parseProofUrls(row.proofUrls)
  proofDialogVisible.value = true
}

// 解析证明材料URLs
const parseProofUrls = (proofUrls: string) => {
  if (!proofUrls) return []
  try {
    return JSON.parse(proofUrls)
  } catch {
    return proofUrls.split(',')
  }
}

// 审核通过
const handleApprove = (row: any) => {
  auditAction.value = 'approve'
  auditForm.remark = ''
  currentAudit.value = row
  auditDialogVisible.value = true
}

// 审核拒绝
const handleReject = (row: any) => {
  auditAction.value = 'reject'
  auditForm.remark = ''
  currentAudit.value = row
  auditDialogVisible.value = true
}

// 确认审核
const confirmAudit = async () => {
  if (auditAction.value === 'reject' && !auditForm.remark) {
    ElMessage.warning('请输入拒绝原因')
    return
  }

  auditLoading.value = true
  try {
    let res: any
    if (auditAction.value === 'approve') {
      res = await approveProfileAudit(currentAudit.value.id, auditForm.remark)
    } else {
      res = await rejectProfileAudit(currentAudit.value.id, auditForm.remark)
    }

    if (res.code === 200) {
      ElMessage.success(auditAction.value === 'approve' ? '审核已通过' : '已拒绝')
      auditDialogVisible.value = false
      fetchList()
    } else {
      ElMessage.error(res.message || '操作失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message || '操作失败')
  } finally {
    auditLoading.value = false
  }
}

onMounted(() => {
  fetchList()
})
</script>

<style scoped>
.profile-audit-page {
  padding: 20px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.page-header h2 {
  font-size: 20px;
  font-weight: 600;
  color: #303133;
}

.audit-stats {
  display: flex;
  gap: 20px;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 16px;
  border-radius: 20px;
  background: #f5f7fa;
}

.stat-item .label {
  color: #909399;
  font-size: 14px;
}

.stat-item .value {
  font-size: 18px;
  font-weight: 600;
}

.stat-item.pending .value { color: #e6a23c; }
.stat-item.approved .value { color: #67c23a; }
.stat-item.rejected .value { color: #f56c6c; }

.filter-toolbar {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
  align-items: center;
}

.psychologist-info {
  display: flex;
  align-items: center;
  gap: 10px;
}

.info-detail .name {
  font-weight: 500;
  color: #303133;
}

.info-detail .username {
  font-size: 12px;
  color: #909399;
}

.change-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.change-item {
  display: flex;
  align-items: center;
}

.change-item .label {
  color: #909399;
  font-size: 12px;
  min-width: 40px;
}

.change-item .value {
  font-size: 13px;
}

.change-item .value.old {
  color: #909399;
  text-decoration: line-through;
}

.change-item .value.new {
  color: #409eff;
  font-weight: 500;
}

.change-item .value.reason {
  color: #909399;
  font-style: italic;
}

.no-proof {
  color: #c0c4cc;
}

.pagination-wrapper {
  display: flex;
  justify-content: flex-end;
  margin-top: 20px;
}

.detail-content {
  padding: 10px 0;
}

.detail-content .value.old {
  color: #909399;
  text-decoration: line-through;
}

.detail-content .value.new {
  color: #409eff;
  font-weight: 500;
}

.proof-section {
  margin-top: 20px;
  padding-top: 20px;
  border-top: 1px solid #ebeef5;
}

.proof-section h4 {
  margin-bottom: 10px;
  color: #303133;
  font-size: 14px;
  font-weight: 600;
}

.proof-images {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.proof-gallery {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
</style>

// apps/admin-portal/src/components/admin/psychologist-admin/ProfileAudit.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { httpClient } from "@/lib/api-admin";

const s = {
  primary: "#409eff", text: "#303133", text2: "#606266", text3: "#909399",
  border: "#dcdfe6", bg: "#f0f2f5", white: "#fff", danger: "#f56c6c",
  success: "#67c23a", warning: "#e6a23c", radius: "4px", shadow: "0 2px 12px rgba(0,0,0,0.06)",
};

type PageResult<T> = { total: number; records: T[]; current: number; size: number; pages: number };

function getStatusLabel(status: number) {
  if (status === 0) return "待审核";
  if (status === 1) return "已通过";
  if (status === 2) return "已拒绝";
  return "未知";
}

function getStatusColor(status: number) {
  if (status === 0) return s.warning;
  if (status === 1) return s.success;
  if (status === 2) return s.danger;
  return s.text3;
}

export function ProfileAudit() {
  const [data, setData] = useState<PageResult<Record<string,unknown>>>({ total:0, records:[], current:1, size:20, pages:0 });
  const [auditVisible, setAuditVisible] = useState(false);
  const [auditingItem, setAuditingItem] = useState<Record<string,unknown>|null>(null);
  const [auditAction, setAuditAction] = useState<"approve"|"reject">("approve");
  const [auditRemark, setAuditRemark] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("");

  const fetchData = useCallback(async (page = 1) => {
    try {
      const query: Record<string, string | number | boolean | null | undefined> = { page, size: 20 };
      if (statusFilter !== "") query.status = Number(statusFilter);
      const res = await httpClient.get<PageResult<Record<string,unknown>>>("/admin/psychologist/audit/list", { query });
      setData(res);
    } catch { /* ignore */ }
  }, [statusFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const openAudit = (row: Record<string,unknown>, action: "approve"|"reject") => {
    setAuditingItem(row);
    setAuditAction(action);
    setAuditRemark("");
    setAuditVisible(true);
  };

  const confirmAudit = async () => {
    if (!auditingItem) return;
    if (auditAction === "reject" && !auditRemark) return;
    try {
      await httpClient.post(`/admin/psychologist/audit/${auditingItem.id}/${auditAction}`, {}, { query: { remark: auditRemark || undefined } });
      setAuditVisible(false);
      fetchData();
    } catch { /* ignore */ }
  };

  return (
    <div style={{ padding:"20px", backgroundColor:s.bg, minHeight:"100%" }}>
      <div style={{ backgroundColor:s.white, borderRadius:"8px", boxShadow:s.shadow, padding:"20px" }}>
        <h3 style={{ margin:"0 0 20px", fontSize:"18px", color:s.text }}>咨询师资料审核</h3>
        <div style={{ display:"flex", gap:"10px", marginBottom:"16px" }}>
          <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}
            style={{ height:"36px", padding:"0 8px", border:`1px solid ${s.border}`, borderRadius:s.radius, fontSize:"13px", color:s.text2 }}>
            <option value="">全部状态</option>
            <option value="0">待审核</option>
            <option value="1">已通过</option>
            <option value="2">已拒绝</option>
          </select>
        </div>
        <table style={{ width:"100%", borderCollapse:"collapse", border:"1px solid #ebeef5" }}>
          <thead>
            <tr style={{ backgroundColor:"#f5f7fa" }}>
              {["ID","咨询师","变更字段","变更内容","审核状态","申请时间","操作"].map(h => <th key={h} style={{ padding:"12px 8px", textAlign:"left", fontSize:"13px", color:s.text3, fontWeight:600, borderBottom:"1px solid #ebeef5" }}>{h}</th>)}
            </tr>
          </thead>
          <tbody>
            {data.records.map((row, i) => (
              <tr key={i} style={{ backgroundColor: i%2===0?"#fff":"#fafafa" }}>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.id as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.psychologistName as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>
                  <span style={{ display:"inline-block", padding:"2px 8px", background:s.bg, borderRadius:"10px", fontSize:"12px", color:s.text2 }}>{row.fieldNameText as string || row.fieldName as string}</span>
                </td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>
                  <div><span style={{ color:s.text3, fontSize:"12px" }}>原值：</span><span style={{ textDecoration:"line-through", color:s.text3 }}>{row.oldValue as string || "(空)"}</span></div>
                  <div><span style={{ color:s.text3, fontSize:"12px" }}>新值：</span><span style={{ color:s.primary, fontWeight:500 }}>{row.newValue as string || "(空)"}</span></div>
                </td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>
                  <span style={{ color: getStatusColor(row.auditStatus as number) }}>{row.auditStatusText as string || getStatusLabel(row.auditStatus as number)}</span>
                </td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.createTime as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5" }}>
                  {(row.auditStatus as number) === 0 && (
                    <>
                      <button onClick={() => openAudit(row, "approve")} style={{ color:s.success, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>通过</button>
                      <button onClick={() => openAudit(row, "reject")} style={{ color:s.danger, border:"none", background:"none", cursor:"pointer" }}>拒绝</button>
                    </>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div style={{ display:"flex", justifyContent:"flex-end", marginTop:"16px", gap:"8px", alignItems:"center" }}>
          <span style={{ fontSize:"13px", color:s.text2 }}>共 {data.total} 条</span>
          <button onClick={() => fetchData(data.current-1)} disabled={data.current<=1} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>上一页</button>
          <span style={{ fontSize:"13px", color:s.text2 }}>{data.current} / {data.pages||1}</span>
          <button onClick={() => fetchData(data.current+1)} disabled={data.current>=data.pages} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>下一页</button>
        </div>
      </div>

      {/* Audit Dialog */}
      {auditVisible && (
        <div style={{ position:"fixed", inset:0, backgroundColor:"rgba(0,0,0,0.5)", display:"flex", justifyContent:"center", alignItems:"center", zIndex:1000 }} onClick={() => setAuditVisible(false)}>
          <div style={{ backgroundColor:s.white, borderRadius:"8px", padding:"24px", width:"500px" }} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ margin:"0 0 20px", fontSize:"18px", color:s.text }}>{auditAction === "approve" ? "通过审核" : "拒绝审核"}</h3>
            <div style={{ marginBottom:"20px" }}>
              <label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>{auditAction === "approve" ? "审核备注（可选）" : "拒绝原因"}</label>
              <textarea value={auditRemark} onChange={(e) => setAuditRemark(e.target.value)} rows={3} placeholder={auditAction === "approve" ? "可选：添加通过备注" : "请输入拒绝原因"} style={{ width:"100%", padding:"8px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, boxSizing:"border-box", resize:"vertical" }} />
            </div>
            <div style={{ display:"flex", justifyContent:"flex-end", gap:"10px" }}>
              <button onClick={() => setAuditVisible(false)} style={{ height:"36px", padding:"0 20px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>取消</button>
              <button onClick={confirmAudit} style={{ height:"36px", padding:"0 20px", backgroundColor: auditAction==="approve"?s.primary:s.danger, color:"#fff", border:"none", borderRadius:s.radius, cursor:"pointer" }}>确认{auditAction==="approve"?"通过":"拒绝"}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
