// AIAdolescentMentalHealthSystemClient/src/views/admin/content/BookManager.vue
<template>
  <div class="book-manager">
    <div class="header">
      <h2>书籍管理</h2>
      <el-button type="primary" @click="handleAdd">新增书籍</el-button>
    </div>

    <div class="search-bar" style="margin-bottom: 20px;">
      <el-select v-model="filterStatus" placeholder="选择状态" style="width: 150px; margin-right: 10px;" clearable @change="fetchBooks">
        <el-option label="全部" value=""></el-option>
        <el-option label="上架" :value="1"></el-option>
        <el-option label="下架" :value="0"></el-option>
      </el-select>
      <el-input v-model="searchQuery" placeholder="搜索书籍标题" style="width: 200px; margin-right: 10px;" @keyup.enter="fetchBooks"></el-input>
      <el-button @click="fetchBooks">搜索</el-button>
    </div>

    <el-table :data="books" v-loading="loading" style="width: 100%">
      <el-table-column prop="id" label="ID" width="80"></el-table-column>
      <el-table-column label="封面" width="100">
        <template #default="scope">
          <el-image
            v-if="scope.row.coverUrl"
            :src="scope.row.coverUrl"
            style="width: 60px; height: 80px;"
            fit="cover"
            :preview-src-list="[scope.row.coverUrl]"
            preview-teleported
          ></el-image>
          <span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column prop="title" label="标题" min-width="200"></el-table-column>
      <el-table-column prop="description" label="简介" min-width="200">
        <template #default="scope">
          <span class="description-text">{{ scope.row.description || '-' }}</span>
        </template>
      </el-table-column>
      <el-table-column prop="viewCount" label="浏览数" width="100"></el-table-column>
      <el-table-column prop="commentCount" label="评论数" width="100"></el-table-column>
      <el-table-column prop="sortOrder" label="排序" width="80"></el-table-column>
      <el-table-column prop="status" label="状态" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.status === 1 ? 'success' : 'info'">
            {{ scope.row.status === 1 ? '上架' : '下架' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="createTime" label="创建时间" width="180"></el-table-column>
      <el-table-column label="操作" width="280" fixed="right">
        <template #default="scope">
          <el-button size="small" @click="handleEdit(scope.row)">编辑</el-button>
          <el-button size="small" @click="handleViewComments(scope.row)">评论管理</el-button>
          <el-button v-if="scope.row.status === 1" size="small" type="warning" @click="handleToggleStatus(scope.row)">下架</el-button>
          <el-button v-else size="small" type="success" @click="handleToggleStatus(scope.row)">上架</el-button>
          <el-button size="small" type="danger" @click="handleDelete(scope.row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <div class="pagination">
      <el-pagination
        v-model:current-page="currentPage"
        v-model:page-size="pageSize"
        :total="total"
        layout="total, prev, pager, next"
        @current-change="fetchBooks"
      ></el-pagination>
    </div>

    <!-- 评论管理对话框 -->
    <el-dialog v-model="commentDialogVisible" title="评论管理" width="800px">
      <div class="comment-header">
        <span>书籍：《{{ currentBookTitle }}》</span>
      </div>
      <el-table :data="comments" v-loading="commentLoading" style="width: 100%;" max-height="400">
        <el-table-column prop="id" label="ID" width="80"></el-table-column>
        <el-table-column prop="userNickname" label="用户" width="120">
          <template #default="scope">
            <div class="user-info">
              <el-avatar :size="24" :src="scope.row.userAvatar">
                <img src="https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png"/>
              </el-avatar>
              <span style="margin-left: 8px;">{{ scope.row.userNickname }}</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="content" label="评论内容"></el-table-column>
        <el-table-column prop="createTime" label="评论时间" width="180"></el-table-column>
        <el-table-column label="操作" width="100" fixed="right">
          <template #default="scope">
            <el-button size="small" type="danger" @click="handleDeleteComment(scope.row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
      <!-- 评论分页 -->
      <div class="pagination" style="margin-top: 15px;">
        <el-pagination
          v-model:current-page="commentPage"
          v-model:page-size="commentSize"
          :total="commentTotal"
          layout="total, prev, pager, next"
          @current-change="fetchComments"
        ></el-pagination>
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { getBookAdminList, deleteBook, updateBook, getBookCommentList, deleteBookComment } from '@/api/adminBook'
import { ElMessage, ElMessageBox } from 'element-plus'

const router = useRouter()
const books = ref<any[]>([])
const loading = ref(false)
const searchQuery = ref('')
const filterStatus = ref<number | ''>('')
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)

// 评论相关
const commentDialogVisible = ref(false)
const commentLoading = ref(false)
const comments = ref<any[]>([])
const currentBookId = ref<number | null>(null)
const currentBookTitle = ref('')
const commentPage = ref(1)
const commentSize = ref(10)
const commentTotal = ref(0)

const fetchBooks = async () => {
  loading.value = true
  try {
    const params: any = {
      page: currentPage.value,
      size: pageSize.value
    }
    if (searchQuery.value) {
      params.keyword = searchQuery.value
    }
    if (filterStatus.value !== '') {
      params.status = filterStatus.value
    }
    const res = await getBookAdminList(params) as any
    if (res.code === 200) {
      books.value = res.data.records
      total.value = res.data.total
    }
  } catch (error) {
    console.error(error)
  } finally {
    loading.value = false
  }
}

const handleAdd = () => {
  router.push('/admin/content/books/create')
}

const handleEdit = (row: any) => {
  router.push(`/admin/content/books/edit/${row.id}`)
}

const handleToggleStatus = async (row: any) => {
  const newStatus = row.status === 1 ? 0 : 1
  const actionText = newStatus === 1 ? '上架' : '下架'
  try {
    const res = await updateBook(row.id, { status: newStatus }) as any
    if (res.code === 200) {
      ElMessage.success(`${actionText}成功`)
      fetchBooks()
    } else {
      ElMessage.error(res.message || `${actionText}失败`)
    }
  } catch (error) {
    ElMessage.error(`${actionText}失败`)
  }
}

const handleDelete = (row: any) => {
  ElMessageBox.confirm('确定删除这本书吗？删除后无法恢复。', '删除确认', { type: 'warning' }).then(async () => {
    try {
      const res = await deleteBook(row.id) as any
      if (res.code === 200) {
        ElMessage.success('删除成功')
        fetchBooks()
      } else {
        ElMessage.error(res.message || '删除失败')
      }
    } catch (error) {
      ElMessage.error('删除失败')
    }
  }).catch(() => {})
}

const handleViewComments = (row: any) => {
  currentBookId.value = row.id
  currentBookTitle.value = row.title
  commentDialogVisible.value = true
  commentPage.value = 1
  fetchComments()
}

const fetchComments = async () => {
  if (!currentBookId.value) return
  commentLoading.value = true
  try {
    const res = await getBookCommentList(currentBookId.value, {
      page: commentPage.value,
      size: commentSize.value
    }) as any
    if (res.code === 200) {
      comments.value = res.data.records
      commentTotal.value = res.data.total
    }
  } catch (error) {
    console.error(error)
  } finally {
    commentLoading.value = false
  }
}

const handleDeleteComment = (row: any) => {
  ElMessageBox.confirm('确定删除这条评论吗？', '删除确认', { type: 'warning' }).then(async () => {
    try {
      const res = await deleteBookComment(row.id) as any
      if (res.code === 200) {
        ElMessage.success('删除成功')
        // 同步减少评论数
        const book = books.value.find(b => b.id === currentBookId.value)
        if (book && book.commentCount > 0) {
          book.commentCount--
        }
        fetchComments()
      } else {
        ElMessage.error(res.message || '删除失败')
      }
    } catch (error) {
      ElMessage.error('删除失败')
    }
  }).catch(() => {})
}

onMounted(() => {
  fetchBooks()
})
</script>

<style scoped>
.book-manager {
  padding: 20px;
}
.header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
}
.pagination {
  margin-top: 20px;
  display: flex;
  justify-content: flex-end;
}
.description-text {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}
.user-info {
  display: flex;
  align-items: center;
}
.comment-header {
  margin-bottom: 15px;
  padding-bottom: 10px;
  border-bottom: 1px solid #ebeef5;
  font-weight: bold;
  color: #409eff;
}
</style>

// apps/admin-portal/src/components/admin/content/BookManager.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { httpClient } from "@/lib/api-admin";

const s = {
  primary: "#409eff", text: "#303133", text2: "#606266", text3: "#909399",
  border: "#dcdfe6", bg: "#f0f2f5", white: "#fff", danger: "#f56c6c",
  success: "#67c23a", warning: "#e6a23c", radius: "4px", shadow: "0 2px 12px rgba(0,0,0,0.06)",
};

type PageResult<T> = { total: number; records: T[]; current: number; size: number; pages: number };

function getStatusLabel(status: number) { return status === 1 ? "上架" : "下架"; }
function getStatusColor(status: number) { return status === 1 ? s.success : s.text3; }

export function BookManager() {
  const [data, setData] = useState<PageResult<Record<string,unknown>>>({ total:0, records:[], current:1, size:20, pages:0 });
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("");
  const router = useRouter();

  const fetchData = useCallback(async (page = 1) => {
    try {
      const query: Record<string, string | number | boolean | null | undefined> = { page, size: 20, keyword: search };
      if (statusFilter !== "") query.status = Number(statusFilter);
      const res = await httpClient.get<PageResult<Record<string,unknown>>>("/admin/book/list", { query });
      setData(res);
    } catch { /* ignore */ }
  }, [search, statusFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleToggleStatus = async (row: Record<string,unknown>) => {
    const newStatus = (row.status as number) === 1 ? 0 : 1;
    try {
      await httpClient.put(`/admin/book/${row.id}`, { status: newStatus });
      fetchData();
    } catch { /* ignore */ }
  };

  const handleDelete = async (id: unknown) => {
    if (!confirm("确认删除？")) return;
    try { await httpClient.delete(`/admin/book/${id}`); fetchData(); } catch { /* ignore */ }
  };

  // Comment management state
  const [commentVisible, setCommentVisible] = useState(false);
  const [commentLoading, setCommentLoading] = useState(false);
  const [comments, setComments] = useState<Record<string,unknown>[]>([]);
  const [currentBookId, setCurrentBookId] = useState<number | null>(null);
  const [currentBookTitle, setCurrentBookTitle] = useState("");
  const [commentPage, setCommentPage] = useState(1);
  const [commentTotal, setCommentTotal] = useState(0);

  const fetchComments = async (page = 1) => {
    if (!currentBookId) return;
    fetchCommentsForBook(currentBookId, page);
  };

  const handleViewComments = (row: Record<string,unknown>) => {
    const bookId = row.id as number;
    setCurrentBookId(bookId);
    setCurrentBookTitle(row.title as string);
    setCommentVisible(true);
    fetchCommentsForBook(bookId, 1);
  };

  const fetchCommentsForBook = async (bookId: number, page = 1) => {
    setCommentLoading(true);
    try {
      const res = await httpClient.get<PageResult<Record<string,unknown>>>(`/book/${bookId}/comment/list`, { query: { page, size: 10 } });
      setComments(res.records);
      setCommentTotal(res.total);
      setCommentPage(page);
    } catch { /* ignore */ }
    finally { setCommentLoading(false); }
  };

  const handleDeleteComment = async (commentId: unknown) => {
    if (!confirm("确认删除该评论？")) return;
    try {
      await httpClient.delete(`/admin/book/comment/${commentId}`);
      fetchComments(commentPage);
      setData(prev => ({
        ...prev,
        records: prev.records.map(r => r.id === currentBookId ? { ...r, commentCount: Math.max(0, ((r.commentCount as number) ?? 0) - 1) } : r),
      }));
    } catch { /* ignore */ }
  };

  return (
    <div style={{ padding:"20px", backgroundColor:s.bg, minHeight:"100%" }}>
      <div style={{ backgroundColor:s.white, borderRadius:"8px", boxShadow:s.shadow, padding:"20px" }}>
        <div style={{ display:"flex", justifyContent:"space-between", marginBottom:"20px" }}>
          <div style={{ display:"flex", gap:"10px" }}>
            <select value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); }}
              style={{ height:"36px", padding:"0 8px", border:`1px solid ${s.border}`, borderRadius:s.radius, fontSize:"13px", color:s.text2 }}>
              <option value="">全部状态</option>
              <option value="1">上架</option>
              <option value="0">下架</option>
            </select>
            <input placeholder="搜索书籍..." value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key==="Enter"&&fetchData()}
              style={{ height:"36px", padding:"0 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, width:"240px", outline:"none" }} />
            <button onClick={() => fetchData()} style={{ height:"36px", padding:"0 20px", backgroundColor:s.primary, color:"#fff", border:"none", borderRadius:s.radius, cursor:"pointer" }}>搜索</button>
          </div>
          <button onClick={() => router.push("/admin/content/books/new")} style={{ height:"36px", padding:"0 20px", backgroundColor:s.primary, color:"#fff", border:"none", borderRadius:s.radius, cursor:"pointer" }}>新增书籍</button>
        </div>
        <table style={{ width:"100%", borderCollapse:"collapse", border:"1px solid #ebeef5" }}>
          <thead>
            <tr style={{ backgroundColor:"#f5f7fa" }}>
              {["ID","封面","书名","简介","浏览数","评论数","排序","状态","创建时间","操作"].map(h => <th key={h} style={{ padding:"12px 8px", textAlign:"left", fontSize:"13px", color:s.text3, fontWeight:600, borderBottom:"1px solid #ebeef5" }}>{h}</th>)}
            </tr>
          </thead>
          <tbody>
            {data.records.map((row, i) => (
              <tr key={i} style={{ backgroundColor: i%2===0?"#fff":"#fafafa" }}>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.id as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5" }}>
                  {row.coverUrl ? <img src={row.coverUrl as string} alt="" style={{ width:"60px", height:"80px", objectFit:"cover", borderRadius:s.radius }} /> : <span style={{ color:s.text3, fontSize:"13px" }}>-</span>}
                </td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.title as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px", maxWidth:"200px", overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{row.description as string || "-"}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.viewCount as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.commentCount as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.sortOrder as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>
                  <span style={{ color: getStatusColor(row.status as number) }}>{getStatusLabel(row.status as number)}</span>
                </td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{row.createTime as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:"1px solid #ebeef5" }}>
                  <button onClick={() => router.push(`/admin/content/books/${row.id}/edit`)} style={{ color:s.primary, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>编辑</button>
                  <button onClick={() => handleViewComments(row)} style={{ color:s.text2, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>评论管理</button>
                  <button onClick={() => handleToggleStatus(row)} style={{ color:s.warning, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>{(row.status as number)===1?"下架":"上架"}</button>
                  <button onClick={() => handleDelete(row.id)} style={{ color:s.danger, border:"none", background:"none", cursor:"pointer" }}>删除</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div style={{ display:"flex", justifyContent:"flex-end", marginTop:"16px", gap:"8px", alignItems:"center" }}>
          <span style={{ fontSize:"13px", color:s.text2 }}>共 {data.total} 条</span>
          <button onClick={() => fetchData(data.current-1)} disabled={data.current<=1} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>上一页</button>
          <span style={{ fontSize:"13px", color:s.text2 }}>{data.current} / {data.pages||1}</span>
          <button onClick={() => fetchData(data.current+1)} disabled={data.current>=data.pages} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>下一页</button>
        </div>
      </div>

      {/* Comment Management Dialog */}
      {commentVisible && (
        <div style={{ position:"fixed", inset:0, backgroundColor:"rgba(0,0,0,0.5)", display:"flex", justifyContent:"center", alignItems:"center", zIndex:1000 }} onClick={() => setCommentVisible(false)}>
          <div style={{ backgroundColor:s.white, borderRadius:"8px", padding:"24px", width:"800px", maxHeight:"80vh", overflow:"auto" }} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ margin:"0 0 16px", fontSize:"18px", color:s.text }}>评论管理 - 《{currentBookTitle}》</h3>
            {commentLoading ? (
              <div style={{ textAlign:"center", padding:"40px", color:s.text3 }}>加载中...</div>
            ) : (
              <>
                <table style={{ width:"100%", borderCollapse:"collapse", border:"1px solid #ebeef5" }}>
                  <thead>
                    <tr style={{ backgroundColor:"#f5f7fa" }}>
                      {["ID","用户","评论内容","评论时间","操作"].map(h => <th key={h} style={{ padding:"10px 8px", textAlign:"left", fontSize:"13px", color:s.text3, fontWeight:600, borderBottom:"1px solid #ebeef5" }}>{h}</th>)}
                    </tr>
                  </thead>
                  <tbody>
                    {comments.map((c, i) => (
                      <tr key={i} style={{ backgroundColor: i%2===0?"#fff":"#fafafa" }}>
                        <td style={{ padding:"10px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{c.id as string}</td>
                        <td style={{ padding:"10px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{c.userNickname as string}</td>
                        <td style={{ padding:"10px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{c.content as string}</td>
                        <td style={{ padding:"10px 8px", borderBottom:"1px solid #ebeef5", fontSize:"13px" }}>{c.createTime as string}</td>
                        <td style={{ padding:"10px 8px", borderBottom:"1px solid #ebeef5" }}>
                          <button onClick={() => handleDeleteComment(c.id)} style={{ color:s.danger, border:"none", background:"none", cursor:"pointer" }}>删除</button>
                        </td>
                      </tr>
                    ))}
                    {comments.length === 0 && (
                      <tr><td colSpan={5} style={{ textAlign:"center", padding:"20px", color:s.text3, fontSize:"13px" }}>暂无评论</td></tr>
                    )}
                  </tbody>
                </table>
                <div style={{ display:"flex", justifyContent:"flex-end", marginTop:"12px", gap:"8px", alignItems:"center" }}>
                  <span style={{ fontSize:"13px", color:s.text2 }}>共 {commentTotal} 条</span>
                  <button onClick={() => fetchComments(commentPage-1)} disabled={commentPage<=1} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>上一页</button>
                  <span style={{ fontSize:"13px", color:s.text2 }}>{commentPage} / {Math.max(1, Math.ceil(commentTotal/10))}</span>
                  <button onClick={() => fetchComments(commentPage+1)} disabled={commentPage>=Math.ceil(commentTotal/10)} style={{ padding:"6px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>下一页</button>
                </div>
              </>
            )}
            <div style={{ display:"flex", justifyContent:"flex-end", marginTop:"16px" }}>
              <button onClick={() => setCommentVisible(false)} style={{ height:"36px", padding:"0 20px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>关闭</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
