// AIAdolescentMentalHealthSystemClient/src/views/admin/psychologist/QualificationManager.vue
<template>
  <div class="qualification-admin-page">
    <div class="page-header">
      <h2>资质类型管理</h2>
      <el-button type="primary" @click="openDialog('add')">
        <el-icon><Plus /></el-icon> 新增资质
      </el-button>
    </div>

    <el-table :data="qualificationList" v-loading="loading" stripe>
      <el-table-column prop="id" label="ID" width="80"></el-table-column>
      <el-table-column prop="name" label="资质名称" min-width="200"></el-table-column>
      <el-table-column prop="code" label="资质代码" width="150"></el-table-column>
      <el-table-column prop="description" label="描述" min-width="250"></el-table-column>
      <el-table-column prop="sortOrder" label="排序" width="80"></el-table-column>
      <el-table-column label="状态" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.status === 1 ? 'success' : 'info'" size="small">
            {{ scope.row.status === 1 ? '启用' : '禁用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="150" fixed="right">
        <template #default="scope">
          <el-button size="small" type="primary" link @click="openDialog('edit', scope.row)">编辑</el-button>
          <el-button size="small" type="danger" link @click="deleteQualification(scope.row.id)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <div class="pagination-wrapper">
      <el-pagination
        v-model:current-page="currentPage"
        v-model:page-size="pageSize"
        :total="total"
        :page-sizes="[10, 20, 50]"
        layout="total, sizes, prev, pager, next"
        @size-change="fetchList"
        @current-change="fetchList"
      />
    </div>

    <el-dialog v-model="dialogVisible" :title="dialogType === 'add' ? '新增资质' : '编辑资质'" width="500px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="资质名称" required>
          <el-input v-model="form.name" placeholder="请输入资质名称" />
        </el-form-item>
        <el-form-item label="资质代码" required>
          <el-input v-model="form.code" placeholder="请输入资质代码" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="form.description" type="textarea" :rows="3" placeholder="请输入描述" />
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="form.sortOrder" :min="0" />
        </el-form-item>
        <el-form-item label="状态">
          <el-radio-group v-model="form.status">
            <el-radio :label="1">启用</el-radio>
            <el-radio :label="0">禁用</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="saveQualification" :loading="loading">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import request from '@/utils/request'

const loading = ref(false)
const qualificationList = ref<any[]>([])
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)

const dialogVisible = ref(false)
const dialogType = ref<'add' | 'edit'>('add')
const form = reactive({
  id: null as number | null,
  name: '',
  code: '',
  description: '',
  sortOrder: 0,
  status: 1
})

const fetchList = async () => {
  loading.value = true
  try {
    const res: any = await request({
      url: '/api/admin/psychologist/qualifications',
      method: 'get'
    })
    if (res.code === 200) {
      qualificationList.value = res.data || []
      total.value = qualificationList.value.length
    }
  } catch (error: any) {
    ElMessage.error(error.message || '获取列表失败')
  } finally {
    loading.value = false
  }
}

const openDialog = (type: 'add' | 'edit', row?: any) => {
  dialogType.value = type
  if (type === 'add') {
    form.id = null
    form.name = ''
    form.code = ''
    form.description = ''
    form.sortOrder = 0
    form.status = 1
  } else {
    form.id = row.id
    form.name = row.name
    form.code = row.code
    form.description = row.description || ''
    form.sortOrder = row.sortOrder || 0
    form.status = row.status
  }
  dialogVisible.value = true
}

const saveQualification = async () => {
  if (!form.name || !form.code) {
    ElMessage.warning('请填写必填项')
    return
  }
  loading.value = true
  try {
    const res: any = await request({
      url: dialogType.value === 'add' ? '/api/admin/psychologist/qualification' : `/api/admin/psychologist/qualification/${form.id}`,
      method: dialogType.value === 'add' ? 'post' : 'put',
      data: form
    })
    if (res.code === 200) {
      ElMessage.success(dialogType.value === 'add' ? '添加成功' : '更新成功')
      dialogVisible.value = false
      fetchList()
    } else {
      ElMessage.error(res.message || '操作失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message || '操作失败')
  } finally {
    loading.value = false
  }
}

const deleteQualification = async (id: number) => {
  try {
    await ElMessageBox.confirm('确定要删除该资质吗？', '提示', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    const res: any = await request({
      url: `/api/admin/psychologist/qualification/${id}`,
      method: 'delete'
    })
    if (res.code === 200) {
      ElMessage.success('删除成功')
      fetchList()
    } else {
      ElMessage.error(res.message || '删除失败')
    }
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error(error.message || '删除失败')
    }
  }
}

onMounted(() => {
  fetchList()
})
</script>

<style scoped>
.qualification-admin-page {
  padding: 20px;
}
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}
.page-header h2 {
  font-size: 20px;
  font-weight: 600;
  color: #303133;
  margin: 0;
}
.pagination-wrapper {
  display: flex;
  justify-content: flex-end;
  margin-top: 20px;
}
</style>

// apps/admin-portal/src/components/admin/content/QualificationManager.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { httpClient } from "@/lib/api-admin";

import { s } from "@/lib/design-tokens";

type PageResult<T> = { total: number; records: T[]; current: number; size: number; pages: number };

export function QualificationManager() {
  const [data, setData] = useState<PageResult<Record<string,unknown>>>({ total:0, records:[], current:1, size:20, pages:0 });
  const [dialogVisible, setDialogVisible] = useState(false);
  const [detailVisible, setDetailVisible] = useState(false);
  const [editingItem, setEditingItem] = useState<Record<string,unknown>|null>(null);
  const [currentItem, setCurrentItem] = useState<Record<string,unknown>|null>(null);
  const [form, setForm] = useState<Record<string,unknown>>({ name: "", code: "", description: "", sortOrder: "", status: 1 });

  const fetchData = useCallback(async () => {
    try {
      const res = await httpClient.get<Record<string,unknown>[]>("/admin/psychologist/qualifications");
      const arr = Array.isArray(res) ? res : [];
      arr.sort((a, b) => Number(a.id) - Number(b.id));
      setData({ total: arr.length, records: arr, current: 1, size: arr.length, pages: 1 });
    } catch { /* ignore */ }
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  const openAdd = () => { setEditingItem(null); setForm({ name: "", code: "", description: "", sortOrder: "", status: 1 }); setDialogVisible(true); };
  const openEdit = (item: Record<string,unknown>) => { setEditingItem(item); setForm({ name: item.name || "", code: item.code || "", description: item.description || "", sortOrder: item.sortOrder || "", status: (item.status as number) ?? 1 }); setDialogVisible(true); };
  const viewDetail = (item: Record<string,unknown>) => { setCurrentItem(item); setDetailVisible(true); };

  const handleToggleStatus = async (row: Record<string,unknown>) => {
    const newStatus = (row.status as number) === 1 ? 0 : 1;
    try {
      await httpClient.put(`/admin/psychologist/qualification/${row.id}`, { ...row, status: newStatus });
      fetchData();
    } catch { /* ignore */ }
  };

  const handleSave = async () => {
    try {
      if (editingItem) {
        await httpClient.put(`/admin/psychologist/qualification/${editingItem.id}`, form);
      } else {
        await httpClient.post("/admin/psychologist/qualification", form);
      }
      setDialogVisible(false);
      fetchData();
    } catch { /* ignore */ }
  };

  const handleDelete = async (id: unknown) => {
    if (!confirm("确认删除？")) return;
    try { await httpClient.delete(`/admin/psychologist/qualification/${id}`); fetchData(); } catch { /* ignore */ }
  };

  return (
    <div style={{ padding:"20px", backgroundColor:s.bg, minHeight:"100%" }}>
      <div style={{ backgroundColor:s.white, borderRadius:"8px", boxShadow:s.shadow, padding:"20px" }}>
        <div style={{ display:"flex", justifyContent:"space-between", marginBottom:"20px" }}>
          <h3 style={{ margin:0, fontSize:"18px", color:s.text }}>资质管理</h3>
          <button onClick={openAdd} style={{ height:"36px", padding:"0 20px", backgroundColor:s.primary, color:"#fff", border:"none", borderRadius:s.radius, cursor:"pointer" }}>新增资质</button>
        </div>
        <table style={{ width:"100%", borderCollapse:"collapse", border:`1px solid ${s.border}` }}>
          <thead>
            <tr style={{ backgroundColor:s.bg }}>
              {["ID","资质名称","编码","描述","排序","状态","操作"].map(h => <th key={h} style={{ padding:"12px 8px", textAlign:"left", fontSize:"13px", color:s.text3, fontWeight:600, borderBottom:`1px solid ${s.border}` }}>{h}</th>)}
            </tr>
          </thead>
          <tbody>
            {data.records.map((row, i) => (
              <tr key={i} style={{ backgroundColor: i%2===0?"#fff":s.bg }}>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px" }}>{row.id as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px" }}>{row.name as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px" }}>{row.code as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px", maxWidth:"150px", overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{row.description as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px" }}>{row.sortOrder as string}</td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}`, fontSize:"13px" }}>
                  <span style={{ color: (row.status as number)===1?s.success:s.text3 }}>{(row.status as number)===1?"启用":"禁用"}</span>
                </td>
                <td style={{ padding:"12px 8px", borderBottom:`1px solid ${s.border}` }}>
                  <button onClick={() => viewDetail(row)} style={{ color:s.text2, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>详情</button>
                  <button onClick={() => openEdit(row)} style={{ color:s.primary, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>编辑</button>
                  <button onClick={() => handleToggleStatus(row)} style={{ color:s.warning, border:"none", background:"none", cursor:"pointer", marginRight:"8px" }}>{(row.status as number)===1?"禁用":"启用"}</button>
                  <button onClick={() => handleDelete(row.id)} style={{ color:s.danger, border:"none", background:"none", cursor:"pointer" }}>删除</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div style={{ display:"flex", justifyContent:"flex-end", marginTop:"16px", gap:"8px", alignItems:"center" }}>
          <span style={{ fontSize:"13px", color:s.text2 }}>共 {data.total} 条</span>
        </div>
      </div>

      {/* Detail Dialog */}
      {detailVisible && currentItem && (
        <div style={{ position:"fixed", inset:0, backgroundColor:"rgba(0,0,0,0.5)", display:"flex", justifyContent:"center", alignItems:"center", zIndex:1000 }} onClick={() => setDetailVisible(false)}>
          <div style={{ backgroundColor:s.white, borderRadius:"8px", padding:"24px", width:"480px" }} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ margin:"0 0 20px", fontSize:"18px", color:s.text }}>资质详情</h3>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>ID：</span><span style={{ fontSize:"13px" }}>{currentItem.id as string}</span></div>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>名称：</span><span style={{ fontSize:"13px" }}>{currentItem.name as string}</span></div>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>编码：</span><span style={{ fontSize:"13px" }}>{currentItem.code as string}</span></div>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>描述：</span><span style={{ fontSize:"13px" }}>{currentItem.description as string || "-"}</span></div>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>排序：</span><span style={{ fontSize:"13px" }}>{currentItem.sortOrder as string}</span></div>
            <div style={{ marginBottom:"12px" }}><span style={{ fontSize:"13px", color:s.text3 }}>状态：</span><span style={{ fontSize:"13px", color:(currentItem.status as number)===1?s.success:s.text3 }}>{(currentItem.status as number)===1?"启用":"禁用"}</span></div>
            <div style={{ marginBottom:"20px" }}><span style={{ fontSize:"13px", color:s.text3 }}>创建时间：</span><span style={{ fontSize:"13px" }}>{currentItem.createTime as string}</span></div>
            <div style={{ display:"flex", justifyContent:"flex-end" }}>
              <button onClick={() => setDetailVisible(false)} style={{ height:"36px", padding:"0 20px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>关闭</button>
            </div>
          </div>
        </div>
      )}

      {/* Add/Edit Dialog */}
      {dialogVisible && (
        <div style={{ position:"fixed", inset:0, backgroundColor:"rgba(0,0,0,0.5)", display:"flex", justifyContent:"center", alignItems:"center", zIndex:1000 }} onClick={() => setDialogVisible(false)}>
          <div style={{ backgroundColor:s.white, borderRadius:"8px", padding:"24px", width:"480px" }} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ margin:"0 0 20px", fontSize:"18px", color:s.text }}>{editingItem?"编辑资质":"新增资质"}</h3>
            <div style={{ marginBottom:"16px" }}><label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>资质名称</label><input value={form.name as string} onChange={(e) => setForm({...form, name:e.target.value})} style={{ width:"100%", height:"36px", padding:"0 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, boxSizing:"border-box" }} /></div>
            <div style={{ marginBottom:"16px" }}><label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>编码</label><input value={form.code as string} onChange={(e) => setForm({...form, code:e.target.value})} style={{ width:"100%", height:"36px", padding:"0 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, boxSizing:"border-box" }} /></div>
            <div style={{ marginBottom:"16px" }}><label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>描述</label><textarea value={form.description as string} onChange={(e) => setForm({...form, description:e.target.value})} rows={2} style={{ width:"100%", padding:"8px 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, boxSizing:"border-box", resize:"vertical" }} /></div>
            <div style={{ marginBottom:"16px" }}><label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>排序</label><input value={form.sortOrder as string} onChange={(e) => setForm({...form, sortOrder:e.target.value})} style={{ width:"100%", height:"36px", padding:"0 12px", border:`1px solid ${s.border}`, borderRadius:s.radius, boxSizing:"border-box" }} /></div>
            <div style={{ marginBottom:"20px" }}><label style={{ display:"block", marginBottom:"6px", fontSize:"13px", color:s.text2 }}>状态</label><select value={form.status as number} onChange={(e) => setForm({...form, status: Number(e.target.value)})} style={{ width:"100%", height:"36px", padding:"0 12px", border:`1px solid ${s.border}`, borderRadius:s.radius }}><option value={1}>启用</option><option value={0}>禁用</option></select></div>
            <div style={{ display:"flex", justifyContent:"flex-end", gap:"10px" }}>
              <button onClick={() => setDialogVisible(false)} style={{ height:"36px", padding:"0 20px", border:`1px solid ${s.border}`, borderRadius:s.radius, background:s.white, cursor:"pointer" }}>取消</button>
              <button onClick={handleSave} style={{ height:"36px", padding:"0 20px", backgroundColor:s.primary, color:"#fff", border:"none", borderRadius:s.radius, cursor:"pointer" }}>保存</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
